name: build

on:
  push:
    branches:
      - "main"
  pull_request:

permissions: {}

jobs:
  govulncheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./go.mod
          check-latest: true

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: dgryski/semgrep-go
          path: rules

      - name: semgrep
        run: semgrep scan --error --enable-nosem -f ./rules .

  ruleguard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: dgryski/semgrep-go
          path: rules

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./go.mod
          check-latest: true

      - name: setup-ruleguard
        run: go install github.com/quasilyte/go-ruleguard/cmd/ruleguard@latest

      - name: ruleguard
        run: |
          mv rules ../
          go get -u github.com/quasilyte/go-ruleguard/dsl@latest
          ruleguard -c=0 -rules ../rules/ruleguard.rules.go ./...

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./go.mod
          check-latest: true

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-tparse
        run: go install github.com/mfridman/tparse@latest

      - name: setup
        run: |
          task setup
          task build

      - name: test
        run: ./scripts/test.sh
      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
