name: release

on:
  workflow_dispatch:
    inputs:
      release-as:
        description: "semver type of the release"
        type: choice
        options:
          - patch
          - minor
          - major
        default: none
        required: true
      prerelease:
        description: "release as prerelease"
        type: boolean
        required: true
        default: true
      prerelease-suffix:
        description: suffix for your prerelease versions
        type: string
        required: false
        default: beta

permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ">=1.20.6"
      - uses: actions/cache@v4
        with:
          path: |
            ./dist/*.deb
            ./dist/*.rpm
            ./dist/*.apk
          key: ${{ github.ref }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ inputs.release-as }}
          PRERELEASE: ${{ inputs.prerelease }}
          PRERELEASE_SUFFIX: ${{ inputs.prerelease-suffix }}
          VERBOSE: true
          DRY_RUN: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          ORG_NAME: ${{ github.repository_owner }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_owner }}
          path: dist/*
