name: release

on:
  workflow_dispatch:
    inputs:
      release-as:
        description: "semver type of the release"
        type: choice
        options:
          - patch
          - minor
          - major
        default: none
        required: true
      prerelease:
        description: "release as prerelease"
        type: boolean
        required: true
        default: true
      prerelease-suffix:
        description: suffix for your prerelease versions
        type: string
        required: false
        default: beta

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.22'
          check-latest: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea # 1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ inputs.release-as }}
          PRERELEASE: ${{ inputs.prerelease }}
          PRERELEASE_SUFFIX: ${{ inputs.prerelease-suffix }}
          VERBOSE: true
          DRY_RUN: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          ORG_NAME: ${{ github.repository_owner }}

      - name: Upload assets
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ github.repository_owner }}
          path: dist/*
